trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: SyncToAzureDevOps
  steps:
  - checkout: self

  - script: |
      git config  --global user.email "harik@systechusa.com"
      git config  --global user.name "Hariprasad29kc"
      echo "Git Configuration:"
      git config --list
      echo "Remote URLs:"
      git remote -v
      git remote set-url origin https://$GITHUB_PAT@github.com/Hariprasad29kc/CI_CD_pipe
      git fetch github
      if git rev-parse --verify --quiet github/main; then
        git checkout main
        git reset --hard github/main
        git push --force origin main
    else
      echo "The 'main' branch does not exist in the Github repo."
    fi 
  displayName: 'Sync to Azure DevOpsdqwd21tyt'
