trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: SyncToAzureDevOps
  steps:
  - checkout: self

  - script: |
      git config  --global user.email "harik@systechusa.com"
      git config  --global user.name "Hariprasad29kc"
      echo "Git Configuration:"
      git config --list
      echo "Remote URLs:"
      git remote -v
      git remote set-url origin https://$GITHUB_PAT@github.com/Hariprasad29kc/CI_CD_pipe
      git push https://dev.azure.com/harik0533/cicd2/_git/cicd2 main:main
    displayName: 'Sync to Azure DevOpsdqwd21tyt'
