trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: SyncToAzureDevOps
  steps:
  - checkout: self

  - script: |
      git config  --global user.email "harik@systechusa.com"
      git config  --global user.name "Hariprasad29kc"
      echo "Git Configuration:"
      git config --list
      echo "Remote URLs:"
      git remote -v
      git push origin HEAD:refs/head/main --force
    displayName: 'Sync to Azure DevOpsdqwd21'
