trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: SyncToAzureDevOps
  steps:
  - checkout: self

  - script: |
      git config  --global user.email "harik@systechusa.com"
      git config  --global user.name "Hariprasad29kc"
      git push --set-upstream origin HEAD:refs/head/main --force
    displayName: 'Sync to Azure DevOps'